# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('promotions_nmb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='promotions.Category')),
                ('category_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='promotions.Category')),
                ('category_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='promotions.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('price_initial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('purchases_nmb', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('discount_type', models.CharField(choices=[('A', 'All'), ('C', 'Clearance')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('faq', models.TextField(blank=True, default=None, null=True)),
                ('what_you_get', models.TextField(blank=True, default=None, null=True)),
                ('map', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('coordinates_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('coordinates_longtitude', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('dt_expiration', models.DateTimeField()),
                ('rating_total', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_nmb', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('purchases_nmb', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_top_seller', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions_img')),
                ('is_main', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItemScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Review')),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.ReviewItem')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.Promotion'),
        ),
    ]
