# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('purchases_nmb', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
